// src/renderer/src/views/CartView.tsx
import { Button } from 'primereact/button'
import Section from '../components/Section'
import IconCard from '../components/IconCard'
import Counter from '../components/Counter'
import { useCart } from '../contexts/CartContext'
import { useStepper } from '../contexts/StepperContext'
import { Icones } from '../constants/formularios'
import type { SimuladorFormKeys } from '../types/models'

export default function CartView(): React.JSX.Element {
  const cart = useCart()
  const stepper = useStepper()

  const next = (): void => {
    if (cart.items.length > 0) stepper.next()
  }

  const renderCard = (key: SimuladorFormKeys, label: string, icon?: string): React.JSX.Element => (
    <IconCard className="shadow-3 w-12rem" label={label} icon={icon || Icones[key]}>
      <Counter
        value={cart.countByType(key)}
        onIncrement={() => cart.addItem(key)}
        onDecrement={() => cart.removeItem(key)}
      />
    </IconCard>
  )

  return (
    <div>
      <Section titulo="Lavandaria" descricao="Recolha e entrega ao domicílio" icon="lavandaria">
        {renderCard('tapete', 'Tapete / Carpete')}
      </Section>

      <Section
        titulo="Serviço ao Domicílio"
        descricao="Deslocação gratuita"
        icon="servico-ao-domicilio"
      >
        <div className="flex flex-wrap gap-2 justify-content-around">
          {renderCard('sofa', 'Sofá')}
          {renderCard('colchao', 'Colchão')}
          {renderCard('estruturaCabeceira', 'Estrutura/Cabeceira')}
          {renderCard('cortinados', 'Cortinados')}
          {renderCard('cadeiras', 'Cadeiras')}
          {renderCard('pousaPes', 'Pousa-pés')}
          {renderCard('puff', 'Puff')}
          {renderCard('carpete', 'Tapete / Carpete')}
        </div>
      </Section>

      <div className="text-center mt-4">
        <Button
          label="Avançar"
          icon="pi pi-arrow-right"
          iconPos="right"
          className="w-full sm:w-20rem"
          onClick={next}
          disabled={cart.items.length === 0}
        />
      </div>
    </div>
  )
}

// carpetclean-calc-main/src/app/views/cart-view/cart-view.component.ts
import { Component, OnInit, inject, signal } from '@angular/core';
import { SectionComponent } from '../../components/section/section.component';
import { ButtonModule } from 'primeng/button';
import { CounterComponent } from '../../components/counter/counter.component';
import { IconCardComponent } from '../../components/icon-card/icon-card.component';
import { StepperService } from '../../services/stepper.service';
import { Formularios, Icones, SimuladorFormKeys } from '../../constants/Formularios';
import { CommonModule } from '@angular/common';
import { FormService } from '../../services/form.service';

@Component({
  selector: 'app-cart-view',
  standalone: true,
  imports: [CommonModule, SectionComponent, IconCardComponent, CounterComponent, ButtonModule],
  templateUrl: './cart-view.component.html',
  styleUrl: './cart-view.component.scss'
})
export class CartViewComponent implements OnInit {
  form = inject(FormService);
  stepper = inject(StepperService);

  icones = Icones;

  initialValues = signal<Partial<Record<SimuladorFormKeys, number>>>({});

  ngOnInit(): void {
    this.form.form().controls.forEach(f => {
      this.initialValues.update(values => { 
        const key = f.controls.$type.getRawValue();
        values[key] =  (values[key] || 0) + 1
        return values;
      });
    });
  }

  onIncrement(name: SimuladorFormKeys) {
    this.form.form.update(f => {
      f.controls.push(Formularios[name].factory());
      return f;
    });
  }
  onDecrement(name: SimuladorFormKeys) {
    this.form.form.update(f => {
      const removeIndex = f.controls.findIndex(c => c.value.$type == name);
      f.removeAt(removeIndex);
      return f;
    });
  }

  next() {
    if(this.form.form().controls.length > 0) this.stepper.next();
    else {

    }
  }
}

<app-section titulo="Lavandaria" descricao="Recolha e entrega ao domicílio" icon="lavandaria">
    <app-icon-card class="shadow-3 w-12rem" label="Tapete / Carpete" [icon]="icones['tapete']">
      <app-counter
        [initialValue]="initialValues().tapete"
        (onIncrement)="onIncrement('tapete')"
        (onDecrement)="onDecrement('tapete')"
      />
    </app-icon-card> 
  </app-section>
  <app-section titulo="Serviço ao Domicílio" descricao="Deslocação Gratuíta" icon="servico-ao-domicilio">
    <div class="flex flex-wrap gap-2 justify-content-around">
      <app-icon-card class="shadow-3 w-12rem" label="Sofá" [icon]="icones['sofa']">
        <app-counter
          [initialValue]="initialValues().sofa"
          (onIncrement)="onIncrement('sofa')"
          (onDecrement)="onDecrement('sofa')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Colchão" [icon]="icones['colchao']">
        <app-counter
          [initialValue]="initialValues().colchao"
          (onIncrement)="onIncrement('colchao')"
          (onDecrement)="onDecrement('colchao')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Estrutura/Cabeceira" [icon]="icones['estruturaCabeceira']">
        <app-counter
          [initialValue]="initialValues().estruturaCabeceira"
          (onIncrement)="onIncrement('estruturaCabeceira')"
          (onDecrement)="onDecrement('estruturaCabeceira')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Cortinados" [icon]="icones['cortinados']">
        <app-counter
          [initialValue]="initialValues().cortinados"
          (onIncrement)="onIncrement('cortinados')"
          (onDecrement)="onDecrement('cortinados')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Cadeiras" [icon]="icones['cadeiras']">
        <app-counter
          [initialValue]="initialValues().cadeiras"
          (onIncrement)="onIncrement('cadeiras')"
          (onDecrement)="onDecrement('cadeiras')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Pousa-pés" [icon]="icones['pousaPes']">
        <app-counter
          [initialValue]="initialValues().pousaPes"
          (onIncrement)="onIncrement('pousaPes')"
          (onDecrement)="onDecrement('pousaPes')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Puff" [icon]="icones['puff']">
        <app-counter
          [initialValue]="initialValues().puff"
          (onIncrement)="onIncrement('puff')"
          (onDecrement)="onDecrement('puff')"
        />
      </app-icon-card>
      <app-icon-card class="shadow-3 w-12rem" label="Tapete / Carpete" [icon]="icones['carpete']">
        <app-counter
          [initialValue]="initialValues().carpete"
          (onIncrement)="onIncrement('carpete')"
          (onDecrement)="onDecrement('carpete')"
        />
      </app-icon-card>
    </div>
  </app-section>
  <div class="text-center">
    <p-button label="Avançar" (onClick)="next()"></p-button>
  </div>
