// carpetclean-calc-main/src/app/components/counter/counter.component.ts
import { Component, EventEmitter, Input, OnInit, Output, input, signal } from '@angular/core';

@Component({
  selector: 'app-counter',
  standalone: true,
  imports: [],
  templateUrl: './counter.component.html',
  styleUrl: './counter.component.scss'
})
export class CounterComponent implements OnInit {
  protected _count = signal(0);

  initialValue = input<number| undefined>();

  @Input()
  max = Number.MAX_VALUE;
  @Input()
  min = 0;
  @Output()
  protected onCounterChange = new EventEmitter<number>();
  @Output()
  protected onIncrement = new EventEmitter<void>();
  @Output()
  protected onDecrement = new EventEmitter<void>();

  public count = this._count.asReadonly();
  ngOnInit(): void {
      this._count.set(this.initialValue() || this.min);
  }

  public increment(inc: number = 1) {
    if(this._count() >= this.max ) return;
    this._count.update(v => v + inc);
    this.onCounterChange.emit(this._count());
    this.onIncrement.emit();
  }
  public decrement(inc: number = 1) {
    if(this._count() <= this.min ) return;
    this._count.update(v => v - inc);
    this.onCounterChange.emit(this._count());
    this.onDecrement.emit();
  }
}

<div class="flex align-items-center gap-2 border-round-md surface-300 py-1 px-2 my-1">
    <span class="cursor-pointer" (click)="decrement()">-</span>
    <span>{{ count() }}</span>
    <span class="cursor-pointer" (click)="increment()">+</span>
</div>

// src/renderer/src/components/Counter.tsx
type CounterProps = {
  value: number
  min?: number
  max?: number
  onIncrement?: () => void
  onDecrement?: () => void
}

export default function Counter({
  value,
  min = 0,
  max = Number.MAX_VALUE,
  onIncrement,
  onDecrement
}: CounterProps): React.JSX.Element {
  const increment = (): void => {
    if (value >= max) return
    onIncrement?.()
  }

  const decrement = (): void => {
    if (value <= min) return
    onDecrement?.()
  }

  return (
    <div className="flex align-items-center gap-2 border-round-md surface-300 py-1 px-2 my-1">
      <span className="cursor-pointer" onClick={decrement}>
        -
      </span>
      <span>{value}</span>
      <span className="cursor-pointer" onClick={increment}>
        +
      </span>
    </div>
  )
}
