// src/renderer/src/views/CheckoutView.tsx
import { useEffect, useMemo, useState } from 'react'
import { Button } from 'primereact/button'
import { RadioButton } from 'primereact/radiobutton'
import { useCart } from '../contexts/CartContext'
import { useStepper } from '../contexts/StepperContext'
import { useSimulador } from '../hooks/useSimulador'
import { OFERTAS } from '../constants/ofertas'
import type { SimuladorFormKeys } from '../types/models'

function formatCurrency(value: number): string {
  return new Intl.NumberFormat('pt-PT', { style: 'currency', currency: 'EUR' }).format(value)
}

export default function CheckoutView(): React.JSX.Element {
  const cart = useCart()
  const stepper = useStepper()
  const simulador = useSimulador()
  const [adicionalSelected, setAdicionalSelected] = useState<boolean>(false)

  useEffect(() => {
    simulador.calcular(cart.items)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const possuiOferta = useMemo(() => {
    if (cart.items.length !== 1) return null
    const type = cart.items[0].$type as SimuladorFormKeys
    return OFERTAS[type] || null
  }, [cart.items])

  useEffect(() => {
    if (possuiOferta && adicionalSelected) {
      simulador.setAdicional(possuiOferta.valor)
    } else {
      simulador.setAdicional(0)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [adicionalSelected, possuiOferta])

  return (
    <div>
      <div>
        <i className="pi pi-arrow-left cursor-pointer" onClick={() => stepper.prev()}></i>
      </div>
      <hr />
      <div className="flex flex-column gap-2">
        <div>
          {simulador.items.map((item, index) => (
            <div key={index}>
              <div className="flex justify-content-between mb-1">
                <span>{item.descricao}</span>
                <div>
                  <span className="cursor-pointer" onClick={() => simulador.deleteItem(item)}>
                    <i className="pi pi-trash mx-2 text-red-400"></i>
                  </span>
                </div>
              </div>
              <div className="text-sm ml-4 text-700 mb-2">
                {item.resumo.detalhes.map((detalhe, di) => (
                  <div key={di} className="flex justify-content-between">
                    <span>{detalhe.detalhe}</span>
                    <span>{formatCurrency(detalhe.valor)}</span>
                  </div>
                ))}
              </div>
              <div className="flex justify-content-end">
                <span>{formatCurrency(item.resumo.total)}</span>
              </div>
              <hr />
            </div>
          ))}
        </div>

        <div className="flex flex-column align-items-center justify-content-center">
          {simulador.items.length > 0 ? (
            <>
              <div className="mb-4 mt-2 text-center">
                Valor Total (Servicos a Domicilio): {formatCurrency(simulador.totalDomicilio)}
                <br />
                {simulador.descontosDomicilio > 0 && (
                  <>
                    Descontos (Servico a Domicilio): {formatCurrency(simulador.descontosDomicilio)}
                    <br />
                  </>
                )}
                <br />
                Valor Total (Servicos Lavanderia): {formatCurrency(simulador.totalLavanderia)}
                <br />
                {simulador.descontosLavanderia > 0 && (
                  <>
                    Descontos: {formatCurrency(simulador.descontosLavanderia)}
                    <br />
                  </>
                )}
                <br />
                Valor final c/ IVA: {formatCurrency(simulador.totalComDesconto)}
                <br />
                <br />
                *Valores c/ IVA incluso
                <br />
              </div>

              {possuiOferta && (
                <div>
                  <div className="text-center w-20rem mb-4">
                    98% dos nossos clientes compra o tratamento Anti-acaros, por apenas{' '}
                    <span>{formatCurrency(possuiOferta.valor)}</span>
                  </div>
                  <div className="flex gap-2 mb-4 justify-content-center">
                    <span>
                      Sim, quero
                      <RadioButton
                        value={true}
                        onChange={() => setAdicionalSelected(true)}
                        checked={adicionalSelected === true}
                      />
                    </span>
                    <span>
                      Nao, obrigado
                      <RadioButton
                        value={false}
                        onChange={() => setAdicionalSelected(false)}
                        checked={adicionalSelected === false}
                      />
                    </span>
                  </div>
                  <div className="mb-6 font-bold text-lg text-center">
                    Valor Total: {formatCurrency(simulador.finalTotal)}
                  </div>
                </div>
              )}
            </>
          ) : (
            <div>Carrinho Vazio.</div>
          )}
        </div>

        <div className="flex justify-content-center gap-2">
          {simulador.items.length > 0 ? (
            <>
              <Button
                label="Adicionar Servico"
                severity="secondary"
                onClick={() => stepper.to(0)}
              />
              <Button label="Finalizar" onClick={() => stepper.next()} />
            </>
          ) : (
            <Button label="Ir para Homepage" onClick={() => stepper.to(0)} />
          )}
        </div>
      </div>
    </div>
  )
}

// carpetclean-calc-main/src/app/views/checkout-view/checkout-view.component.ts
import { Component, OnInit, computed, inject } from '@angular/core';
import { ButtonModule } from 'primeng/button';
import { ResultadoItem, SimuladorService } from '../../services/simulador.service';
import { CommonModule } from '@angular/common';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { StepperService } from '../../services/stepper.service';
import { FormService } from '../../services/form.service';
import { IAbstractFormValue } from '../../constants/Formularios';
import { OfertaService } from '../../services/oferta.service';
import { RadioButtonModule  } from 'primeng/radiobutton';
import { FormControl, FormGroup, ReactiveFormsModule } from '@angular/forms';

@Component({
  selector: 'app-checkout-view',
  standalone: true,
  imports: [CommonModule, ButtonModule, ProgressSpinnerModule, RadioButtonModule, ReactiveFormsModule],
  templateUrl: './checkout-view.component.html',
  styleUrl: './checkout-view.component.scss'
})
export class CheckoutViewComponent implements OnInit {
  simulador = inject(SimuladorService);
  stepper = inject(StepperService);
  form = inject(FormService);
  oferta = inject(OfertaService);

  possuiOferta = computed(() => {
    if(this.form.form().controls.length > 1) return null;
    return this.oferta.getOferta(this.form.form().controls[0].value.$type)
  });
  
  adicionalForm = new FormGroup({
    adicional: new FormControl<boolean>(false)
  });

  totalComDesconto = computed(() => {
    return this.totalDomicilio() + this.totalLavanderia() - this.descontosLavanderia() - this.descontosDomicilio();
  });

  totalLavanderia = computed(() => {
    const simulador = this.simulador.items();
    if(simulador.loading) return 0;
    return simulador.value.filter(e => e.tipo == 'lavanderia').reduce((acc, curr) => acc + curr.resumo.total, 0)
  })

  descontosLavanderia = computed(() => {
    const simulador = this.simulador.items();
    if(simulador.loading) return 0;
    return simulador.value.filter(e => e.tipo == 'lavanderia').reduce((acc, curr) => acc + curr.resumo.descontoLimpeza, 0)

  })

  totalDomicilio = computed(() => {
    const items = this.simulador.items();
    if(items.loading) return 0;
    return items.value.filter(e => e.tipo == 'domicilio').reduce((acc , curr)=> acc + curr.resumo.total , 0)
  });

  descontosDomicilio = computed(() => {
    const total = this.totalDomicilio();
    const tabelaDesconto = [
      { desconto: 200, value: 0 },
      { desconto: 350, value: 10 },
      { desconto: 700, value: 15 },
      { desconto: Number.MAX_VALUE, value: 20 },
    ]

    const categoriaDesconto = tabelaDesconto.sort(e => e.desconto).find(e => e.desconto >= total )?.value || 0;
    return  total * categoriaDesconto / 100;
  });

  ngOnInit(): void {
    this.form.form().updateValueAndValidity();
    const form = this.form.form().value as IAbstractFormValue[];
    this.simulador.calcular(form).subscribe();

    this.adicionalForm.controls.adicional.valueChanges.subscribe(v => {
      const adicional = v ? this.possuiOferta()!.valor : 0;
      this.simulador.adicional.set(adicional);
    });
  }

  deleteItem(item: ResultadoItem) {
    this.simulador.items.update(i => i.loading ? i : { value: i.value.filter(v => v != item) });
  }

  voltar() {
    this.stepper.prev();
  }

  voltarHome() {
    this.stepper.to(0);
  }

  finalizar() {
    this.stepper.next();
  }
}

<div>
    <i class="pi pi-arrow-left" (click)="voltar()"></i>
</div>
<hr>
<div class="flex flex-column gap-2">
    @if(simulador.items().value; as items) {
        <div>
            @for (item of items; track $index) {
                <div class="flex justify-content-between mb-1">
                    <span>{{ item.descricao }}</span>
                    <div>
                        <span (click)="deleteItem(item)"><i class="pi pi-trash mx-2 text-red-400"></i></span>
                    </div>
                </div>
                <div class="text-sm ml-4 text-700 mb-2">

                    @for (detalhe of item.resumo.detalhes; track $index) {
                        <div class="flex justify-content-between">
                            <span>{{ detalhe.detalhe }}</span>
                            <span>{{ detalhe.valor | currency: 'EUR' }}</span>
                        </div>
                    }
                </div>
                <div class="flex justify-content-end">
                    <span>{{ item.resumo.total | currency: 'EUR' }}</span>
                </div>
                <hr>
            }
        </div>
        <div class="flex flex-column align-items-center justify-content-center">
            @if(items.length > 0) {
                <div class="mb-4 mt-2 text-center">
                    Valor Total (Serviços a Domicilio): {{ totalDomicilio() | currency: 'EUR' }}<br>
                    @if(descontosDomicilio(); as descontos) {
                        Descontos (Serviço a Domicilio): {{ descontos | currency: 'EUR' }}<br>
                    }
                    <br>
                    Valor Total (Serviços Lavanderia): {{ totalLavanderia() | currency: 'EUR' }}<br>
                    @if(descontosLavanderia(); as descontos) {
                        Descontos: {{ descontos | currency: 'EUR' }}<br>
                    }
                    <br>
                    Valor final c/ IVA: {{ totalComDesconto() | currency: 'EUR' }}<br>
                    <br>
                    *Valores c/ IVA incluso<br>
                </div>
                @if(possuiOferta(); as oferta) {
                    <div>
                        <div class="text-center w-20rem mb-4">
                            98% dos nossos clientes compra o tratamento Anti-ácaros, por apenas <span>{{oferta.valor | currency: 'EUR'}}</span>
                        </div>
                        <form class="flex gap-2 mb-4 justify-content-center" [formGroup]="adicionalForm">
                            <span>
                                Sim, quero
                                <p-radioButton
                                    formControlName="adicional"
                                    [value]="true"
                                     />
                                </span>
                                <span>
                                    Não, obrigado
                                    <p-radioButton
                                    [value]="false"
                                    formControlName="adicional"
                                     />
                            </span>
                        </form>
                        <div class="mb-6 font-bold text-lg text-center">
                            Valor Total: {{ this.simulador.final().value| currency: 'EUR'}}
                        </div>
                    </div>
                }
            } @else {
                <div>
                    Carrinho Vazio.
                </div>
            }
        </div>
        <div class="flex justify-content-center gap-2">
            @if(items.length > 0) {
                <p-button label="Adicionar Serviço" severity="secondary" (onClick)="voltarHome()"></p-button>
                <p-button label="Finalizar" (onClick)="finalizar()"></p-button>
            } @else {
                <p-button label="Ir para Homepage" (onClick)="voltarHome()"></p-button>
            }
        </div>
    } @else if(simulador.items().loading){
        <div class="text-center">
            <p-progressSpinner class="p-4" styleClass="w-4rem h-4rem" strokeWidth="5" styleClass="text-primary"  animationDuration="1s"></p-progressSpinner>
        </div>
    }
</div>
