// src/renderer/src/components/Section.tsx
import type { ReactNode } from 'react'

type SectionProps = {
  titulo: string
  descricao: string
  icon: string
  children: ReactNode
}

export default function Section({
  titulo,
  descricao,
  icon,
  children
}: SectionProps): React.JSX.Element {
  const src = new URL(`../assets/icons/${icon}.svg`, import.meta.url).href

  return (
    <div>
      <img src={`${src}#svgView(viewBox(40,50,100,75))`} width={120} height={60} alt={titulo} />
      <div className="flex gap-2 align-items-center">
        <span className="font-bold">{titulo}</span>
        <i className="pi pi-chevron-right"></i>
        <hr className="flex-1" />
      </div>
      <small>
        <span>{descricao}</span>
      </small>
      <div className="flex gap-3 justify-content-center py-4">{children}</div>
    </div>
  )
}

// carpetclean-calc-main/src/app/components/section/section.component.ts
import { Component, computed, input } from '@angular/core';
import { IconComponent } from '../icon/icon.component';

@Component({
  selector: 'app-section',
  standalone: true,
  imports: [IconComponent],
  templateUrl: './section.component.html',
  styleUrl: './section.component.scss'
})
export class SectionComponent {
  titulo = input.required<string>();
  descricao = input.required<string>(); 
  icon = input.required<string>();
  src = computed(() => `/assets/icons/${this.icon()}.svg#svgView(viewBox(40,50,100,75))`);
}

<div>
    <img [src]="src()" width="120" height="60">
    <!-- <app-icon [icon]="icon()"></app-icon> -->
    <div class="flex gap-2 align-items-center">
        <span class="font-bold">{{ titulo() }}</span>
        <i class="pi pi-chevron-right"></i>
        <hr class="flex-1">
    </div>
    <small>
        <span>{{ descricao() }}</span>
    </small>
    <div class="flex gap-3 justify-content-center py-4">
        <ng-content></ng-content>
    </div>
</div>
