// carpetclean-calc-main/src/app/views/cadastro-view/cadastro-view.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { StepperService } from '../../services/stepper.service';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { SimuladorService } from '../../services/simulador.service';
import { CadastroService } from '../../services/cadastro.service';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { InputMaskModule } from 'primeng/inputmask';
import { DropdownModule } from 'primeng/dropdown';

export type PaisType = {
  nome: string;
  codigo: string;
  prefix: string;
}

@Component({
  selector: 'app-cadastro-view',
  standalone: true,
  imports: [
    CommonModule,
    InputTextModule,
    ButtonModule,
    ReactiveFormsModule,
    ProgressSpinnerModule,
    InputMaskModule,
    DropdownModule
  ],
  templateUrl: './cadastro-view.component.html',
  styleUrl: './cadastro-view.component.scss'
})
export class CadastroViewComponent implements OnInit {
  stepper = inject(StepperService);
  simulador = inject(SimuladorService);
  cadastro = inject(CadastroService);

  get cadastroCache() {
    const storageData = localStorage.getItem('_cadastro');
    if(storageData) return JSON.parse(storageData) as typeof this.formCadastro.value;
    return null;
  }


  countries: PaisType[] =  [
    { nome: 'Portugal', prefix: '+351', codigo: 'PT' },
    { nome: 'Brasil', prefix: '+55', codigo: 'BR' },
    { nome: 'França', prefix: '+33', codigo: 'FR' },
    { nome: 'Itália', prefix: '+39', codigo: 'IT' },
    { nome: 'Marrocos', prefix: '+212', codigo: 'MA' },
    { nome: 'Alemanha', prefix: '+49', codigo: 'DE' },
    { nome: 'Espanha', prefix: '+34', codigo: 'ES' },
    { nome: 'Argélia', prefix: '+213', codigo: 'DZ' }
];

  loading = signal(false);

  formCadastro = new FormGroup({
    primeiroNome: new FormControl<string>('', { nonNullable: true, validators: [Validators.required] }),
    ultimoNome: new FormControl<string>('', { nonNullable: true, validators: [Validators.required] }),
    telefone: new FormControl<string>('', { nonNullable: true, validators: [Validators.required] }),
    email: new FormControl<string>('', { nonNullable: true, validators: [Validators.required, Validators.email] }),
    morada: new FormControl<string>('', { nonNullable: true }),
    pais: new FormControl<string>('+351', { nonNullable: true }),
    codigoPostal: new FormControl<string>('', { nonNullable: true }),
    localidade: new FormControl<string>('', { nonNullable: true }),
    total: new FormControl(this.simulador.total().value, { nonNullable: true }),
    items: new FormControl(this.simulador.items().value, { nonNullable: true })
  });

  ngOnInit(): void {
    if(this.cadastroCache) {
      this.formCadastro.patchValue({
        primeiroNome: this.cadastroCache.primeiroNome,
        ultimoNome: this.cadastroCache.ultimoNome,
        telefone: this.cadastroCache.telefone,
        email: this.cadastroCache.email,
        morada: this.cadastroCache.morada,
        pais: this.cadastroCache.pais,
        codigoPostal: this.cadastroCache.codigoPostal,
        localidade: this.cadastroCache.localidade,
      })
    }
  }

  enviar() {
    this.formCadastro.updateValueAndValidity();
    this.formCadastro.markAllAsTouched();
    if(this.formCadastro.invalid) return;
    localStorage.setItem('_cadastro', JSON.stringify(this.formCadastro.getRawValue()))
    this.loading.set(true);
    this.cadastro.enviar(this.formCadastro.value).subscribe(() => {
      this.loading.set(false);
      this.stepper.next();
    })
  }

  voltar() {
    this.stepper.prev();
  }
}

@if(loading()){
    <div class="text-center">
        <p-progressSpinner class="p-4" styleClass="w-4rem h-4rem" strokeWidth="5" styleClass="text-primary"  animationDuration="1s"></p-progressSpinner>
    </div>
}@else {
<div class="flex justify-content-between">
    <i class="pi pi-arrow-left" (click)="voltar()"></i>
    <div>
        <span class="font-bold">Valor Total: {{ simulador.final().value| currency: 'EUR' }}</span>
    </div>
</div>
<hr>
<div class="py-5 flex justify-content-center align-items-center">
    <span>Insira os seus dados</span>
</div>
<form [formGroup]="formCadastro">
    <div class="grid">
        <div class="col-12 md:col-6">
            <label class="block mb-1" for="primeiroNome">Primeiro Nome *</label>
            <input pInputText class="w-full" type="text" id="primeiroNome" placeholder="Escreva o primeiro Nome" [formControl]="formCadastro.controls.primeiroNome"/>
        </div>
        <div class="col-12 md:col-6">
            <label class="block mb-1" for="ultimoNome">Último Nome *</label>
            <input pInputText class="w-full" type="text" id="ultimoNome" placeholder="Escreva o último Nome" [formControl]="formCadastro.controls.ultimoNome" />
        </div>
        <div class="col-12 md:col-6">
            <div class="flex gap-2">
                <div>
                    <label class="block mb-1" for="pais">País *</label>
                    <p-dropdown 
                        name="pais"
                        [options]="countries"
                        styleClass="w-8rem"
                        [formControl]="formCadastro.controls.pais"
                        optionLabel="nome"
                        optionValue="prefix"
                        dataKey="codigo"
                        placeholder=" ">
                            <ng-template pTemplate="selectedItem" let-pais>
                                @if(formCadastro.controls.pais.value) {
                                    <div class="flex align-items-center gap-2">
                                        <img
                                        src="https://primefaces.org/cdn/primeng/images/demo/flag/flag_placeholder.png"
                                        [class]="'flag flag-' + pais.codigo.toLowerCase()"
                                        style="width: 18px;height: 12px;" />
                                        <span>{{pais.prefix}}</span>
                                    </div>
                                }
                            </ng-template>
                            <ng-template let-pais pTemplate="item">
                                <div class="flex align-items-center gap-2">
                                    <img 
                                        src="https://primefaces.org/cdn/primeng/images/demo/flag/flag_placeholder.png"
                                        [class]="'flag flag-' + pais.codigo.toLowerCase()"
                                        style="width: 18px;height: 12px;" />
                                        <span>{{pais.prefix}}</span>
                                </div>
                            </ng-template>
                    </p-dropdown>
                </div>
                <div class="flex-1">
                    <label class="block mb-1" for="telefone">Telefone *</label>
                    <p-inputMask styleClass="w-full" id="telefone" mask="999 999 999" [formControl]="formCadastro.controls.telefone" placeholder="Escreva o telefone"></p-inputMask>
                </div>
            </div>
        </div>
        <div class="col-12 md:col-6">
            <label class="block mb-1" for="email">Email *</label>
            <input pInputText class="w-full" type="text" id="email" placeholder="Escreva o Email" [formControl]="formCadastro.controls.email" />
        </div>
        <div class="col-12">
            <label class="block mb-1" for="morada">Morada</label>
            <input pInputText class="w-full" type="text" id="morada" placeholder="Escreva a morada" [formControl]="formCadastro.controls.morada" />
        </div>
        <div class="col-12 md:col-6">
            <label class="block mb-1" for="codigo-postal">Codigo Postal</label>
            <p-inputMask styleClass="w-full" id="codigo-postal" mask="9999-999" [formControl]="formCadastro.controls.codigoPostal" placeholder="0000-000"></p-inputMask>
        </div>
        <div class="col-12 md:col-6">
            <label class="block mb-1" for="localidade">Localidade</label>
            <input pInputText class="w-full" type="text" id="localidade" placeholder="Escreva a localidade" [formControl]="formCadastro.controls.localidade" />
        </div>
    </div>
    <div class="text-center">
        <p-button styleClass="w-full sm:w-auto" label="Enviar" (onClick)="enviar()"></p-button>
    </div>
</form>
}

// src/renderer/src/views/CadastroView.tsx
import { useState } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { Button } from 'primereact/button'
import { InputText } from 'primereact/inputtext'
import { InputMask } from 'primereact/inputmask'
import { Dropdown } from 'primereact/dropdown'
import { useStepper } from '../contexts/StepperContext'

type PaisType = {
  nome: string
  codigo: string
  prefix: string
}

type CadastroFormData = {
  primeiroNome: string
  ultimoNome: string
  telefone: string
  email: string
  morada: string
  pais: string
  codigoPostal: string
  localidade: string
}

const countries: PaisType[] = [
  { nome: 'Portugal', prefix: '+351', codigo: 'PT' },
  { nome: 'Brasil', prefix: '+55', codigo: 'BR' },
  { nome: 'Franca', prefix: '+33', codigo: 'FR' },
  { nome: 'Italia', prefix: '+39', codigo: 'IT' },
  { nome: 'Marrocos', prefix: '+212', codigo: 'MA' },
  { nome: 'Alemanha', prefix: '+49', codigo: 'DE' },
  { nome: 'Espanha', prefix: '+34', codigo: 'ES' },
  { nome: 'Argelia', prefix: '+213', codigo: 'DZ' }
]

function getCadastroCache(): Partial<CadastroFormData> | null {
  const storageData = localStorage.getItem('_cadastro')
  if (storageData) return JSON.parse(storageData)
  return null
}

export default function CadastroView(): React.JSX.Element {
  const stepper = useStepper()
  const [loading, setLoading] = useState(false)

  const cached = getCadastroCache()

  const { control, handleSubmit } = useForm<CadastroFormData>({
    defaultValues: {
      primeiroNome: cached?.primeiroNome || '',
      ultimoNome: cached?.ultimoNome || '',
      telefone: cached?.telefone || '',
      email: cached?.email || '',
      morada: cached?.morada || '',
      pais: cached?.pais || '+351',
      codigoPostal: cached?.codigoPostal || '',
      localidade: cached?.localidade || ''
    }
  })

  const onSubmit = (data: CadastroFormData): void => {
    localStorage.setItem('_cadastro', JSON.stringify(data))
    setLoading(true)
    // Skip Bitrix24 submission - just advance to confirmation
    setTimeout(() => {
      setLoading(false)
      stepper.next()
    }, 300)
  }

  if (loading) {
    return (
      <div className="text-center">
        <i className="pi pi-spin pi-spinner" style={{ fontSize: '3rem' }}></i>
      </div>
    )
  }

  return (
    <div>
      <div className="flex justify-content-between">
        <i className="pi pi-arrow-left cursor-pointer" onClick={() => stepper.prev()}></i>
      </div>
      <hr />
      <div className="py-5 flex justify-content-center align-items-center">
        <span>Insira os seus dados</span>
      </div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <div className="grid">
          <div className="col-12 md:col-6">
            <label className="block mb-1" htmlFor="primeiroNome">
              Primeiro Nome *
            </label>
            <Controller
              name="primeiroNome"
              control={control}
              rules={{ required: true }}
              render={({ field }) => (
                <InputText
                  id="primeiroNome"
                  className="w-full"
                  placeholder="Escreva o primeiro Nome"
                  {...field}
                />
              )}
            />
          </div>
          <div className="col-12 md:col-6">
            <label className="block mb-1" htmlFor="ultimoNome">
              Ultimo Nome *
            </label>
            <Controller
              name="ultimoNome"
              control={control}
              rules={{ required: true }}
              render={({ field }) => (
                <InputText
                  id="ultimoNome"
                  className="w-full"
                  placeholder="Escreva o ultimo Nome"
                  {...field}
                />
              )}
            />
          </div>
          <div className="col-12 md:col-6">
            <div className="flex gap-2">
              <div>
                <label className="block mb-1" htmlFor="pais">
                  Pais *
                </label>
                <Controller
                  name="pais"
                  control={control}
                  render={({ field }) => (
                    <Dropdown
                      id="pais"
                      options={countries}
                      optionLabel="nome"
                      optionValue="prefix"
                      className="w-8rem"
                      value={field.value}
                      onChange={(e) => field.onChange(e.value)}
                      placeholder=" "
                      itemTemplate={(option) => (
                        <div className="flex align-items-center gap-2">
                          <span>{option.prefix}</span>
                        </div>
                      )}
                      valueTemplate={(option) =>
                        option ? (
                          <div className="flex align-items-center gap-2">
                            <span>{option.prefix}</span>
                          </div>
                        ) : (
                          <span>&nbsp;</span>
                        )
                      }
                    />
                  )}
                />
              </div>
              <div className="flex-1">
                <label className="block mb-1" htmlFor="telefone">
                  Telefone *
                </label>
                <Controller
                  name="telefone"
                  control={control}
                  rules={{ required: true }}
                  render={({ field }) => (
                    <InputMask
                      id="telefone"
                      className="w-full"
                      mask="999 999 999"
                      placeholder="Escreva o telefone"
                      value={field.value}
                      onChange={(e) => field.onChange(e.value)}
                    />
                  )}
                />
              </div>
            </div>
          </div>
          <div className="col-12 md:col-6">
            <label className="block mb-1" htmlFor="email">
              Email *
            </label>
            <Controller
              name="email"
              control={control}
              rules={{ required: true }}
              render={({ field }) => (
                <InputText id="email" className="w-full" placeholder="Escreva o Email" {...field} />
              )}
            />
          </div>
          <div className="col-12">
            <label className="block mb-1" htmlFor="morada">
              Morada
            </label>
            <Controller
              name="morada"
              control={control}
              render={({ field }) => (
                <InputText
                  id="morada"
                  className="w-full"
                  placeholder="Escreva a morada"
                  {...field}
                />
              )}
            />
          </div>
          <div className="col-12 md:col-6">
            <label className="block mb-1" htmlFor="codigoPostal">
              Codigo Postal
            </label>
            <Controller
              name="codigoPostal"
              control={control}
              render={({ field }) => (
                <InputMask
                  id="codigoPostal"
                  className="w-full"
                  mask="9999-999"
                  placeholder="0000-000"
                  value={field.value}
                  onChange={(e) => field.onChange(e.value)}
                />
              )}
            />
          </div>
          <div className="col-12 md:col-6">
            <label className="block mb-1" htmlFor="localidade">
              Localidade
            </label>
            <Controller
              name="localidade"
              control={control}
              render={({ field }) => (
                <InputText
                  id="localidade"
                  className="w-full"
                  placeholder="Escreva a localidade"
                  {...field}
                />
              )}
            />
          </div>
        </div>
        <div className="text-center">
          <Button type="submit" className="w-full sm:w-auto" label="Enviar" />
        </div>
      </form>
    </div>
  )
}
