// carpetclean-calc-main/src/app/views/form-view/form-view.component.ts
import { Component, computed, inject } from '@angular/core';
import { StepperService } from '../../services/stepper.service';
import { Formularios, ISimuladorForm } from '../../constants/Formularios';
import { CommonModule } from '@angular/common';
import { TabViewModule } from 'primeng/tabview';
import { TapeteFormComponent } from '../forms/tapete-form/tapete-form.component';
import { SofaFormComponent } from '../forms/sofa-form/sofa-form.component';
import { ColchaoFormComponent } from '../forms/colchao-form/colchao-form.component';
import { EstruturaCabeceiraFormComponent } from '../forms/estrutura-cabeceira-form/estrutura-cabeceira-form.component';
import { CortinadosFormComponent } from '../forms/cortinados-form/cortinados-form.component';
import { CadeirasFormComponent } from '../forms/cadeiras-form/cadeiras-form.component';
import { PousaPesFormComponent } from '../forms/pousa-pes-form/pousa-pes-form.component';
import { PuffFormComponent } from '../forms/puff-form/puff-form.component';
import { CarpeteFormComponent } from '../forms/carpete-form/carpete-form.component';
import { ButtonModule } from 'primeng/button';
import { FormService } from '../../services/form.service';
import { IconComponent } from '../../components/icon/icon.component';

@Component({
  selector: 'app-form-view',
  standalone: true,
  imports: [
    CommonModule,
    TabViewModule,
    TapeteFormComponent,
    SofaFormComponent,
    ColchaoFormComponent,
    EstruturaCabeceiraFormComponent,
    CortinadosFormComponent,
    CadeirasFormComponent,
    PousaPesFormComponent,
    PuffFormComponent,
    ButtonModule,
    CarpeteFormComponent,
    IconComponent
  ],
  templateUrl: './form-view.component.html',
  styleUrl: './form-view.component.scss'
})
export class FormViewComponent {
  stepper = inject(StepperService);
  form = inject(FormService);

  FORMS = Formularios;

  tabIndex = 0;

  avancar(f: ISimuladorForm) {
    if(f.invalid) return;
    if(this.form.form().length == (this.tabIndex + 1)) {
      this.stepper.next()
    } else {
      this.tabIndex++;
    }
  }

  voltar() {
    this.stepper.prev()
  }
}

<span class="cursor-pointer" (click)="voltar()"><i class="pi pi-arrow-left"></i></span>
<p-tabView [(activeIndex)]="tabIndex" [scrollable]="true"  styleClass="tabview-custom">
    @for (f of form.form().controls; track $index;) {
        @if (f.value.$type; as type) {
            <p-tabPanel>
                <ng-template pTemplate="header">
                    <app-icon [icon]="FORMS[type].icone"></app-icon>
                    <span class="ml-2">{{ FORMS[type].nome }}</span>
                </ng-template>
                <ng-container *ngComponentOutlet="FORMS[type].component; inputs: { form: f }"></ng-container>
                <div class="text-center mt-4">
                    <p-button [disabled]="f.invalid" label="Avançar" (onClick)="avancar(f)"></p-button>
                </div>
            </p-tabPanel>
        }
    }
</p-tabView>

// src/renderer/src/views/FormView.tsx
import { useState } from 'react'
import { TabView, TabPanel } from 'primereact/tabview'
import { Button } from 'primereact/button'
import { useCart } from '../contexts/CartContext'
import { useStepper } from '../contexts/StepperContext'
import { Formularios } from '../constants/formularios'
import Icon from '../components/Icon'
import type {
  IAbstractFormValue,
  SimuladorFormKeys,
  TapeteFormValue,
  CarpeteFormValue,
  CortinadoFormValue
} from '../types/models'
import TapeteForm from './forms/TapeteForm'
import SofaForm from './forms/SofaForm'
import ColchaoForm from './forms/ColchaoForm'
import EstruturaCabeceiraForm from './forms/EstruturaCabeceiraForm'
import CortinadosForm from './forms/CortinadosForm'
import CadeirasForm from './forms/CadeirasForm'
import PousaPesForm from './forms/PousaPesForm'
import PuffForm from './forms/PuffForm'
import CarpeteForm from './forms/CarpeteForm'

function renderForm(
  type: SimuladorFormKeys,
  values: IAbstractFormValue,
  onChange: (values: IAbstractFormValue) => void
): React.JSX.Element {
  switch (type) {
    case 'tapete':
      return <TapeteForm values={values} onChange={onChange} />
    case 'sofa':
      return <SofaForm values={values} onChange={onChange} />
    case 'colchao':
      return <ColchaoForm values={values} onChange={onChange} />
    case 'estruturaCabeceira':
      return <EstruturaCabeceiraForm values={values} onChange={onChange} />
    case 'cortinados':
      return <CortinadosForm values={values} onChange={onChange} />
    case 'cadeiras':
      return <CadeirasForm values={values} onChange={onChange} />
    case 'pousaPes':
      return <PousaPesForm values={values} onChange={onChange} />
    case 'puff':
      return <PuffForm values={values} onChange={onChange} />
    case 'carpete':
      return <CarpeteForm values={values} onChange={onChange} />
  }
}

export default function FormView(): React.JSX.Element {
  const cart = useCart()
  const stepper = useStepper()
  const [tabIndex, setTabIndex] = useState(0)

  const isFormValid = (item: IAbstractFormValue): boolean => {
    const hasService = item.limpeza || item.impermeabilizacao || item.antiAcaro
    if (!hasService) return false

    if (item.$type === 'tapete' || item.$type === 'carpete') {
      return (item as TapeteFormValue | CarpeteFormValue).medida > 0
    }

    if (item.$type === 'cortinados') {
      return (item as CortinadoFormValue).formato > 0
    }

    return true
  }

  const avancar = (): void => {
    const currentItem = cart.items[tabIndex]
    if (!isFormValid(currentItem)) return

    if (tabIndex === cart.items.length - 1) {
      stepper.next()
    } else {
      setTabIndex(tabIndex + 1)
    }
  }

  return (
    <div>
      <span className="cursor-pointer" onClick={() => stepper.prev()}>
        <i className="pi pi-arrow-left"></i>
      </span>
      <TabView
        activeIndex={tabIndex}
        onTabChange={(e) => setTabIndex(e.index)}
        scrollable
        className="tabview-custom"
      >
        {cart.items.map((item, index) => {
          const type = item.$type
          const formulario = Formularios[type]
          return (
            <TabPanel
              key={index}
              header={
                <span className="flex align-items-center gap-2">
                  <Icon icon={formulario.icone} width={24} height={24} />
                  <span>{formulario.nome}</span>
                </span>
              }
            >
              {renderForm(type, item, (updated) => cart.updateItem(index, updated))}
              <div className="text-center mt-4">
                <Button
                  label="Avancar"
                  onClick={avancar}
                  disabled={!isFormValid(cart.items[tabIndex])}
                />
              </div>
            </TabPanel>
          )
        })}
      </TabView>
    </div>
  )
}
