// carpetclean-calc-main/src/app/views/forms/carpete-form/carpete-form.component.ts
import { CommonModule } from '@angular/common';
import { Component, OnInit, input } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputNumberModule } from 'primeng/inputnumber';
import { RadioButtonModule } from 'primeng/radiobutton';
import { ToggleButtonModule } from 'primeng/togglebutton';
import { IconCardComponent } from '../../../components/icon-card/icon-card.component';
import { CarpeteFormFactory } from '../../../models/CarpeteModels';
import { Nullable } from 'primeng/ts-helpers';
import { IconComponent } from '../../../components/icon/icon.component';

@Component({
  selector: 'app-carpete-form',
  standalone: true,
  imports: [
    CommonModule,
    IconCardComponent,
    InputNumberModule,
    ButtonModule,
    ToggleButtonModule,
    ReactiveFormsModule,
    RadioButtonModule,
    IconComponent
  ],
  templateUrl: './carpete-form.component.html',
  styleUrl: './carpete-form.component.scss'
})
export class CarpeteFormComponent implements OnInit {
  form = input.required<ReturnType<typeof CarpeteFormFactory>>();

  ngOnInit(): void {
    this.form().controls.x.valueChanges.subscribe((x) => {
      const y = (this.form().value.y || 0);
      this.form().controls.medida.setValue((x || 0) * y ) ;
    });
    
    this.form().controls.y.valueChanges.subscribe((y) => {
      const x = this.form().value.x || 0;
      this.form().controls.medida.setValue((y || 0) * x);
    });
    
    this.form().controls.d.valueChanges.subscribe((d) => {
      const diameter = d || 0;
      this.form().controls.medida.setValue((Math.PI * Math.pow(diameter, 2) / 4));
    });
    
    this.form().controls.a.valueChanges.subscribe((a) => {
      const lado = a || 0;
      this.form().controls.medida.setValue(lado * lado);
    });

    this.form().controls.formato.valueChanges.subscribe((formato) => {
      this.form().controls.medida.reset();
      switch(formato) {
        case 'quadrado':
          this.form().controls.a.enable();
          this.form().controls.d.reset(0);
          this.form().controls.a.reset(0);
          this.form().controls.x.reset(0);
          this.form().controls.y.reset(0);
          this.form().controls.x.disable();
          this.form().controls.y.disable();
          this.form().controls.d.disable();
          break;
        case 'redondo':
          this.form().controls.d.enable();
          this.form().controls.d.reset(0);
          this.form().controls.a.reset(0);
          this.form().controls.x.reset(0);
          this.form().controls.y.reset(0);
          this.form().controls.x.disable();
          this.form().controls.y.disable();
          this.form().controls.a.disable();
          break;
        case 'retangulo':
          this.form().controls.x.enable();
          this.form().controls.y.enable();
          this.form().controls.d.reset(0);
          this.form().controls.a.reset(0);
          this.form().controls.x.reset(0);
          this.form().controls.y.reset(0);
          this.form().controls.d.disable();
          this.form().controls.a.disable();
          break;
      }
    });
  }
}

<form [formGroup]="form()">
    <div class="label">1. Formato</div>
    <div class="flex flex-column align-content-center justify-content-center flex-wrap gap-3 sm:flex-row">
        <app-icon-card class="flex-initial border-round-lg surface-300 w-8rem" icon="tapete-retangulo">
            <ng-template #label>
                <span class="block">Retângulo</span>
            </ng-template>
            <p-radioButton formControlName="formato" value="retangulo" />
        </app-icon-card>
        <app-icon-card class="flex-initial border-round-lg surface-300 w-8rem" icon="tapete-quadrado">
            <ng-template #label>
                <span class="block">Quadrado</span>
            </ng-template>
            <p-radioButton formControlName="formato" value="quadrado" />
        </app-icon-card>
        <app-icon-card class="flex-initial border-round-lg surface-300 w-8rem" icon="tapete-redondo">
            <ng-template #label>
                <span class="block">Redondo</span>
            </ng-template>
            <p-radioButton formControlName="formato" value="redondo" />
        </app-icon-card>
    </div>
    <div class="label">2.Serviço</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="limpeza" onLabel="Limpeza" offLabel="Limpeza"></p-toggleButton>
    </div>
    
    <!-- <div class="label">3. Tratamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="impermeabilizacao" onLabel="Impermeabilização" offLabel="Impermeabilização"></p-toggleButton>
    </div> -->
    <div class="label">4.Medida</div>
    <div><span class="block mb-2"><small>Introduza as medidas em centimetros</small></span></div>
    <div class="flex flex-column justify-content-center sm:flex-row flex-wrap gap-3 align-items-center">
        @if (form().controls.formato.value == 'retangulo') {
            <app-icon icon="tapete-metro-retangulo" viewbox="" [width]="140" [height]="140"></app-icon>
            <span class="flex flex-wrap align-items-center gap-2">
                <label for="y">Y</label>
                <span class="relative">
                    <p-inputNumber
                        mode="decimal"
                        formControlName="y"
                        [minFractionDigits]="2"
                        #y
                        inputStyleClass="w-6rem"
                        inputId="y"
                        mode="decimal"
                        [min]="0"/>
                    <small class="cm-label">m</small>    
                </span>
                <label for="x">X</label>
                <span class="relative">
                    <p-inputNumber
                    mode="decimal"
                    formControlName="x"
                    [minFractionDigits]="2"
                    #x
                    inputStyleClass="w-6rem"
                    inputId="x"
                    mode="decimal"
                    [min]="0"/>
                    <small class="cm-label">m</small>    
                </span>
            </span>
        } @else if (form().controls.formato.value == 'quadrado') {
            <app-icon icon="tapete-metro-quadrado" viewbox="" [width]="110" [height]="110"></app-icon>
            <span class="flex flex-wrap align-items-center gap-2">
                <label for="a">Altura</label>
                <span class="relative">
                    <p-inputNumber
                        #a
                        formControlName="a"
                        mode="decimal"
                        [minFractionDigits]="2"
                        inputStyleClass="w-6rem"
                        inputId="a"
                        mode="decimal"
                        [min]="0"
                    />
                    <small class="cm-label">m</small>    
                </span>
            </span>
        } @else if (form().controls.formato.value == 'redondo') {
            <app-icon icon="tapete-metro-redondo" viewbox="" [width]="110" [height]="110"></app-icon>
            <span class="flex flex-wrap align-items-center gap-2">
                <label for="d">Diâmetro</label>
                <span class="relative">
                    <p-inputNumber
                    #d
                    formControlName="d"
                    mode="decimal"
                    [minFractionDigits]="2"
                    inputStyleClass="w-6rem"
                    inputId="d"
                    mode="decimal"
                    [min]="0"
                    />
                    <small class="cm-label">m</small>
                </span>
            </span>
        }
    <span>{{ form().controls.medida.value | number: '1.2-2' }} m²</span>
</div>
</form>

// src/renderer/src/views/forms/CarpeteForm.tsx
import { useEffect } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { RadioButton } from 'primereact/radiobutton'
import { ToggleButton } from 'primereact/togglebutton'
import { InputNumber } from 'primereact/inputnumber'
import IconCard from '../../components/IconCard'
import Icon from '../../components/Icon'
import type { IAbstractFormValue, CarpeteFormValue } from '../../types/models'

type Props = {
  values: IAbstractFormValue
  onChange: (values: IAbstractFormValue) => void
}

export default function CarpeteForm({ values, onChange }: Props): React.JSX.Element {
  const form = values as CarpeteFormValue
  const { control, watch, setValue, getValues } = useForm<CarpeteFormValue>({
    defaultValues: form
  })

  const formato = watch('formato')
  const x = watch('x')
  const y = watch('y')
  const a = watch('a')
  const d = watch('d')
  const medida = watch('medida')
  const limpeza = watch('limpeza')

  useEffect(() => {
    if (formato === 'retangulo') {
      setValue('medida', (x || 0) * (y || 0))
    } else if (formato === 'quadrado') {
      setValue('medida', (a || 0) * (a || 0))
    } else if (formato === 'redondo') {
      setValue('medida', (Math.PI * Math.pow(d || 0, 2)) / 4)
    }
  }, [x, y, a, d, formato, setValue])

  useEffect(() => {
    onChange(getValues())
  }, [formato, x, y, a, d, medida, limpeza, onChange, getValues])

  return (
    <form>
      <div className="label">1. Formato</div>
      <div className="flex flex-column align-content-center justify-content-center flex-wrap gap-3 sm:flex-row">
        <Controller
          name="formato"
          control={control}
          render={({ field }) => (
            <>
              <IconCard
                className="flex-initial border-round-lg surface-300 w-8rem"
                icon="tapete-retangulo"
                labelContent={<span className="block">Retangulo</span>}
              >
                <RadioButton
                  value="retangulo"
                  onChange={(e) => field.onChange(e.value)}
                  checked={field.value === 'retangulo'}
                />
              </IconCard>
              <IconCard
                className="flex-initial border-round-lg surface-300 w-8rem"
                icon="tapete-quadrado"
                labelContent={<span className="block">Quadrado</span>}
              >
                <RadioButton
                  value="quadrado"
                  onChange={(e) => field.onChange(e.value)}
                  checked={field.value === 'quadrado'}
                />
              </IconCard>
              <IconCard
                className="flex-initial border-round-lg surface-300 w-8rem"
                icon="tapete-redondo"
                labelContent={<span className="block">Redondo</span>}
              >
                <RadioButton
                  value="redondo"
                  onChange={(e) => field.onChange(e.value)}
                  checked={field.value === 'redondo'}
                />
              </IconCard>
            </>
          )}
        />
      </div>

      <div className="label">2. Servico</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="limpeza"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Limpeza"
              offLabel="Limpeza"
            />
          )}
        />
      </div>

      <div className="label">4. Medida</div>
      <div>
        <span className="block mb-2">
          <small>Introduza as medidas em metros</small>
        </span>
      </div>
      <div className="flex flex-column justify-content-center sm:flex-row flex-wrap gap-3 align-items-center">
        {formato === 'retangulo' && (
          <>
            <Icon icon="tapete-metro-retangulo" viewbox="" width={140} height={140} />
            <span className="flex flex-wrap align-items-center gap-2">
              <label htmlFor="carpete-y">Y</label>
              <span className="relative">
                <Controller
                  name="y"
                  control={control}
                  render={({ field }) => (
                    <InputNumber
                      inputId="carpete-y"
                      value={field.value}
                      onValueChange={(e) => field.onChange(e.value || 0)}
                      mode="decimal"
                      minFractionDigits={2}
                      min={0}
                      inputClassName="w-6rem"
                    />
                  )}
                />
                <small className="cm-label">m</small>
              </span>
              <label htmlFor="carpete-x">X</label>
              <span className="relative">
                <Controller
                  name="x"
                  control={control}
                  render={({ field }) => (
                    <InputNumber
                      inputId="carpete-x"
                      value={field.value}
                      onValueChange={(e) => field.onChange(e.value || 0)}
                      mode="decimal"
                      minFractionDigits={2}
                      min={0}
                      inputClassName="w-6rem"
                    />
                  )}
                />
                <small className="cm-label">m</small>
              </span>
            </span>
          </>
        )}
        {formato === 'quadrado' && (
          <>
            <Icon icon="tapete-metro-quadrado" viewbox="" width={110} height={110} />
            <span className="flex flex-wrap align-items-center gap-2">
              <label htmlFor="carpete-a">Altura</label>
              <span className="relative">
                <Controller
                  name="a"
                  control={control}
                  render={({ field }) => (
                    <InputNumber
                      inputId="carpete-a"
                      value={field.value}
                      onValueChange={(e) => field.onChange(e.value || 0)}
                      mode="decimal"
                      minFractionDigits={2}
                      min={0}
                      inputClassName="w-6rem"
                    />
                  )}
                />
                <small className="cm-label">m</small>
              </span>
            </span>
          </>
        )}
        {formato === 'redondo' && (
          <>
            <Icon icon="tapete-metro-redondo" viewbox="" width={110} height={110} />
            <span className="flex flex-wrap align-items-center gap-2">
              <label htmlFor="carpete-d">Diametro</label>
              <span className="relative">
                <Controller
                  name="d"
                  control={control}
                  render={({ field }) => (
                    <InputNumber
                      inputId="carpete-d"
                      value={field.value}
                      onValueChange={(e) => field.onChange(e.value || 0)}
                      mode="decimal"
                      minFractionDigits={2}
                      min={0}
                      inputClassName="w-6rem"
                    />
                  )}
                />
                <small className="cm-label">m</small>
              </span>
            </span>
          </>
        )}
        <span>{(medida || 0).toFixed(2)} m2</span>
      </div>
    </form>
  )
}
