// carpetclean-calc-main/src/app/views/forms/cortinados-form/cortinados-form.component.ts
import { Component, input } from '@angular/core';
import { CortinadoFormFactory } from '../../../models/CortinadoModels';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { InputNumberModule } from 'primeng/inputnumber';
import { ToggleButtonModule } from 'primeng/togglebutton';
import { IconComponent } from '../../../components/icon/icon.component';

@Component({
  selector: 'app-cortinados-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    InputNumberModule,
    ToggleButtonModule,
    IconComponent
  ],
  templateUrl: './cortinados-form.component.html',
  styleUrl: './cortinados-form.component.scss'
})
export class CortinadosFormComponent {
  form = input.required<ReturnType<typeof CortinadoFormFactory>>();


  ngOnInit() {
    this.form().controls.x.valueChanges.subscribe(v => {
      this.form().controls.formato.setValue(v || 0);
    })
  }
}

<form [formGroup]="form()">
    <div>
        <div class="label" style="margin-bottom: 0 !important;">1. Formato</div>
        <span class="block mb-2"><small>Introduza as medidas em centimetros</small></span>
    </div>
    <div class="flex flex-column flex-wrap gap-3 align-items-center">
        <span class="flex flex-wrap align-items-center gap-2">
            <app-icon icon="cortinado-medida" viewbox="" [width]="90" [height]="140"></app-icon>
            <label for="x">X</label>
            <span class="relative">
                <p-inputNumber inputStyleClass="w-6rem" inputId="x" mode="decimal" [minFractionDigits]="2" [min]="0" formControlName="x"/>
                <small class="cm-label">m</small>
            </span>
        </span>
        <span>{{ form().value.formato | number: '1.2-2' }} m</span>
    </div>
    <div class="label">2.Serviço</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="limpeza" onLabel="Limpeza" offLabel="Limpeza"></p-toggleButton>
    </div>
    <div class="label">3. Tratamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="impermeabilizacao" onLabel="Impermeabilização" offLabel="Impermeabilização"></p-toggleButton>
    </div>
</form>

// src/renderer/src/views/forms/CortinadosForm.tsx
import { useEffect } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { ToggleButton } from 'primereact/togglebutton'
import { InputNumber } from 'primereact/inputnumber'
import Icon from '../../components/Icon'
import type { IAbstractFormValue, CortinadoFormValue } from '../../types/models'

type Props = {
  values: IAbstractFormValue
  onChange: (values: IAbstractFormValue) => void
}

export default function CortinadosForm({ values, onChange }: Props): React.JSX.Element {
  const form = values as CortinadoFormValue
  const { control, watch, setValue, getValues } = useForm<CortinadoFormValue>({
    defaultValues: form
  })

  const x = watch('x')
  const limpeza = watch('limpeza')
  const impermeabilizacao = watch('impermeabilizacao')
  const formato = watch('formato')

  useEffect(() => {
    setValue('formato', x || 0)
  }, [x, setValue])

  useEffect(() => {
    onChange(getValues())
  }, [x, limpeza, impermeabilizacao, formato, onChange, getValues])

  return (
    <form>
      <div>
        <div className="label" style={{ marginBottom: 0 }}>
          1. Formato
        </div>
        <span className="block mb-2">
          <small>Introduza as medidas em metros</small>
        </span>
      </div>
      <div className="flex flex-column flex-wrap gap-3 align-items-center">
        <span className="flex flex-wrap align-items-center gap-2">
          <Icon icon="cortinado-medida" viewbox="" width={90} height={140} />
          <label htmlFor="cortinado-x">X</label>
          <span className="relative">
            <Controller
              name="x"
              control={control}
              render={({ field }) => (
                <InputNumber
                  inputId="cortinado-x"
                  value={field.value}
                  onValueChange={(e) => field.onChange(e.value || 0)}
                  mode="decimal"
                  minFractionDigits={2}
                  min={0}
                  inputClassName="w-6rem"
                />
              )}
            />
            <small className="cm-label">m</small>
          </span>
        </span>
        <span>{(formato || 0).toFixed(2)} m</span>
      </div>

      <div className="label">2. Servico</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="limpeza"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Limpeza"
              offLabel="Limpeza"
            />
          )}
        />
      </div>

      <div className="label">3. Tratamento</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="impermeabilizacao"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Impermeabilizacao"
              offLabel="Impermeabilizacao"
            />
          )}
        />
      </div>
    </form>
  )
}
