// carpetclean-calc-main/src/app/views/forms/puff-form/puff-form.component.ts
import { Component, input } from '@angular/core';
import { PuffFormFactory } from '../../../models/PuffModels';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule } from '@angular/forms';
import { ToggleButtonModule } from 'primeng/togglebutton';

@Component({
  selector: 'app-puff-form',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    ToggleButtonModule,
  ],
  templateUrl: './puff-form.component.html',
  styleUrl: './puff-form.component.scss'
})
export class PuffFormComponent {
  form = input.required<ReturnType<typeof PuffFormFactory>>()
}

<form [formGroup]="form()">
    <div class="label">1.Acabamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="acabamento" onLabel="Tecido" offLabel="Tecido"></p-toggleButton>
    </div>
    <div class="label">2.Serviço</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="limpeza" onLabel="Limpeza" offLabel="Limpeza"></p-toggleButton>
    </div>
    <div class="label">3. Tratamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="impermeabilizacao" onLabel="Impermeabilização" offLabel="Impermeabilização"></p-toggleButton>
    </div>
</form>

// src/renderer/src/views/forms/PuffForm.tsx
import { useEffect } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { ToggleButton } from 'primereact/togglebutton'
import type { IAbstractFormValue, PuffFormValue } from '../../types/models'

type Props = {
  values: IAbstractFormValue
  onChange: (values: IAbstractFormValue) => void
}

export default function PuffForm({ values, onChange }: Props): React.JSX.Element {
  const form = values as PuffFormValue
  const { control, watch, getValues } = useForm<PuffFormValue>({
    defaultValues: form
  })

  const limpeza = watch('limpeza')
  const impermeabilizacao = watch('impermeabilizacao')

  useEffect(() => {
    onChange(getValues())
  }, [limpeza, impermeabilizacao, onChange, getValues])

  return (
    <form>
      <div className="label">1. Acabamento</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <ToggleButton
          className="w-full sm:w-12rem"
          checked={true}
          disabled
          onLabel="Tecido"
          offLabel="Tecido"
        />
      </div>

      <div className="label">2. Serviço</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="limpeza"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Limpeza"
              offLabel="Limpeza"
            />
          )}
        />
      </div>

      <div className="label">3. Tratamento</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="impermeabilizacao"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Impermeabilização"
              offLabel="Impermeabilização"
            />
          )}
        />
      </div>
    </form>
  )
}
