// carpetclean-calc-main/src/app/views/forms/sofa-form/sofa-form.component.ts
import { Component, computed, input, signal } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputNumberModule } from 'primeng/inputnumber';
import { RadioButtonModule } from 'primeng/radiobutton';
import { IconCardComponent } from '../../../components/icon-card/icon-card.component';
import { SofaFormFactory } from '../../../models/SofaModels';
import { CounterComponent } from '../../../components/counter/counter.component';
import { CommonModule } from '@angular/common';
import { ToggleButtonModule } from 'primeng/togglebutton';
import { IconComponent } from '../../../components/icon/icon.component';

@Component({
  selector: 'app-sofa-form',
  standalone: true,
  imports: [
    FormsModule,
    ReactiveFormsModule,
    RadioButtonModule,
    InputNumberModule,
    ButtonModule,
    ToggleButtonModule,
    IconCardComponent,
    IconComponent,
    CounterComponent,
    CommonModule
  ],
  templateUrl: './sofa-form.component.html',
  styleUrl: './sofa-form.component.scss'
})
export class SofaFormComponent {
  form = input.required<ReturnType<typeof SofaFormFactory>>();

  iconSize = signal(30)
  sofa = signal(`sofa-1`);
  
  increment() {
    let lugares = this.form().controls.lugares.value || 0;
    this.form().controls.lugares.setValue(lugares + 1);
    lugares = this.form().controls.lugares.getRawValue() || 0; 
    this.sofa.set(`sofa-${lugares}`);
    this.iconSize.set(25 + lugares * 7);
  }
  decrement() {
    let lugares = this.form().controls.lugares.value || 0;
    this.form().controls.lugares.setValue(lugares - 1);
    lugares = this.form().controls.lugares.getRawValue() || 0; 
    this.sofa.set(`sofa-${lugares}`);
    this.iconSize.set(25 + lugares * 7);
  }
}

<form [formGroup]="form()">
    <div class="label">1. Formato</div>
    <div class="flex justify-content-center">
        <div class="flex flex-column align-content-center flex-wrap shadow-3 w-12rem">
            <div class="flex flex-column p-3 align-items-center h-full">
                <app-icon [icon]="sofa()" class="p-1" viewbox="" [width]="140" [height]="50"></app-icon>
                <div class="py-1">
                    <span class="block">Lugares</span>
                </div>
                <div class="mt-auto">
                    <app-counter 
                    [min]="1"
                    [max]="8"
                    (onIncrement)="increment()"
                    (onDecrement)="decrement()"
                    />
                </div>
            </div>
        </div>
    </div>
    <div class="label">2.Acabamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <div class="w-4rem">
            <label class="block" for="tecido">Tecido</label>
            <p-radioButton formControlName="acabamento" inputId="tecido"  value="tecido" />
        </div>
        <div class="w-4rem">
            <label class="block" for="pele">Pele</label>
            <p-radioButton formControlName="acabamento" inputId="pele"  value="pele" />
        </div>
    </div>
    <div class="label">2.Serviço</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="limpeza" onLabel="Limpeza" offLabel="Limpeza"></p-toggleButton>
    </div>
    <div class="label">3. Tratamento</div>
    <div class="flex flex-wrap gap-3 justify-content-center">
        <p-toggleButton class="w-full sm:w-12rem" styleClass="w-full sm:w-12rem" formControlName="impermeabilizacao" onLabel="Impermeabilização" offLabel="Impermeabilização"></p-toggleButton>
    </div>
</form>

// src/renderer/src/views/forms/SofaForm.tsx
import { useState, useEffect } from 'react'
import { useForm, Controller } from 'react-hook-form'
import { RadioButton } from 'primereact/radiobutton'
import { ToggleButton } from 'primereact/togglebutton'
import Icon from '../../components/Icon'
import Counter from '../../components/Counter'
import type { IAbstractFormValue, SofaFormValue } from '../../types/models'

type Props = {
  values: IAbstractFormValue
  onChange: (values: IAbstractFormValue) => void
}

export default function SofaForm({ values, onChange }: Props): React.JSX.Element {
  const form = values as SofaFormValue
  const { control, watch, setValue, getValues } = useForm<SofaFormValue>({
    defaultValues: form
  })

  const [sofaIcon, setSofaIcon] = useState(`sofa-${form.lugares}`)

  const lugares = watch('lugares')
  const acabamento = watch('acabamento')
  const limpeza = watch('limpeza')
  const impermeabilizacao = watch('impermeabilizacao')

  useEffect(() => {
    onChange(getValues())
  }, [lugares, acabamento, limpeza, impermeabilizacao, onChange, getValues])

  const increment = (): void => {
    const current = getValues('lugares') || 1
    if (current >= 8) return
    const next = current + 1
    setValue('lugares', next)
    setSofaIcon(`sofa-${next}`)
  }

  const decrement = (): void => {
    const current = getValues('lugares') || 1
    if (current <= 1) return
    const next = current - 1
    setValue('lugares', next)
    setSofaIcon(`sofa-${next}`)
  }

  return (
    <form>
      <div className="label">1. Formato</div>
      <div className="flex justify-content-center">
        <div className="flex flex-column align-content-center flex-wrap shadow-3 w-12rem">
          <div className="flex flex-column p-3 align-items-center h-full">
            <Icon icon={sofaIcon} viewbox="" width={140} height={50} />
            <div className="py-1">
              <span className="block">Lugares</span>
            </div>
            <div className="mt-auto">
              <Counter
                min={1}
                max={8}
                value={lugares}
                onIncrement={increment}
                onDecrement={decrement}
              />
            </div>
          </div>
        </div>
      </div>

      <div className="label">2. Acabamento</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="acabamento"
          control={control}
          render={({ field }) => (
            <>
              <label className="radio-option" htmlFor="tecido">
                <span>Tecido</span>
                <RadioButton
                  inputId="tecido"
                  value="tecido"
                  onChange={(e) => field.onChange(e.value)}
                  checked={field.value === 'tecido'}
                />
              </label>
              <label className="radio-option" htmlFor="pele">
                <span>Pele</span>
                <RadioButton
                  inputId="pele"
                  value="pele"
                  onChange={(e) => field.onChange(e.value)}
                  checked={field.value === 'pele'}
                />
              </label>
            </>
          )}
        />
      </div>

      <div className="label">3. Serviço</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="limpeza"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Limpeza"
              offLabel="Limpeza"
            />
          )}
        />
      </div>

      <div className="label">4. Tratamento</div>
      <div className="flex flex-wrap gap-3 justify-content-center">
        <Controller
          name="impermeabilizacao"
          control={control}
          render={({ field }) => (
            <ToggleButton
              className="w-full sm:w-12rem"
              checked={field.value}
              onChange={(e) => field.onChange(e.value)}
              onLabel="Impermeabilização"
              offLabel="Impermeabilização"
            />
          )}
        />
      </div>
    </form>
  )
}
